### ISSUE TITLE
Wrong enum conversion

### ISSUE THREAD

**Issue by cfrim** [jonathanp/csharp-models-to-typescript#14]
Converts this
```
public enum ContentType {
  HTML = 1,
  Text = 2
}
```

Into this (which should have numeric values instead)
```
export enum ContentType {
    HTML = 'HTML',
    Text = 'Text',
}
```

**Comment by cfrim** [comment]
I have implemented a fix for this, which I would like to contribute.

**Comment by jonathanp** [comment]
Some APIs use strings to represent enum values when it's serialized to JSON and some use numbers. I agree that it's reasonable to provide this option behind an option flag. I would be happy to review your solution for this, feel free to open a PR. 😊

**Comment by cfrim** [comment]
Agree :) pull request created with the fix and config flag.

**Comment by jonathanp** [comment]
This is now a part of v0.13.0
