### ISSUE TITLE
Convert enums for member type of class to ts enum.

### ISSUE THREAD

**Issue by alextrukhan** [jonathanp/csharp-models-to-typescript#3]
It will be good to add logic to add Enums for member type of converting class to output .d.ts
For example:
There is class `./Proejct1/Models/TargetDto.cs`
```
public class TargetDto
{
    public RelatedEnum PropName { get; set; }
}
```

and enum `./Proejct2/Models/TargetEnum.cs`
```
public class TargetEnum
{
    First, Second
}
```
and configuration 
```
{
    "include": [
        "./Proejct1/Models/*Dto.cs"
    ],
    "output": "./api.d.ts",
    "camelCase": true,
    "stringLiteralTypesInsteadOfEnums": false
}
```

As result, `api.d.ts` will contain only definition of TargetDto with property `propName ` of type `TargetEnum`, that was not converted to ts enum.

Actual`api.d.ts`:
```
export interface TargetDto {
    propName: TargetEnum;
}
```

Expected  `api.d.ts`:
```
export interface TargetDto {
    propName: TargetEnum;
}

export enum TargetEnum{
    First= 'First',
    Second = 'Second'
}
```

**Comment by jonathanp** [comment]
Yeah we don't resolve dependencies automatically. You have to include the path to the dependency (in your case `./Proejct2/Models/TargetEnum.cs`) in the `include` array in the config file.

It would be a nice feature but not something I plan on building, but if you want to take a shot at it feel free to fork/PR :)
