### ISSUE TITLE
Do I have to buy a licence to use your package?

### ISSUE THREAD

**Issue by jantimon** [jonathanp/csharp-models-to-typescript#7]
It looks like the c# package you are using has to be payed:

<img width="573" alt="schema" src="https://user-images.githubusercontent.com/4113649/51388363-76aa6b80-1b29-11e9-821d-2fee665b1eb8.png">

https://www.newtonsoft.com/store/jsonschema

If I am using this cli do I have to pay or will that be part of their free license?

**Comment by jonathanp** [comment]
Hi @jantimon, you don't have to pay anything

**Comment by jantimon** [comment]
Cool ty - can you please explain why?
